/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct
{
	uint32_t crc:2;
	uint32_t status:1;
	uint32_t payload:12;
	uint32_t bat:3;
	uint32_t sensor:3;
	uint32_t longAddr:8;
	uint32_t shortAddr:2;
	uint32_t addrMode:1;
} Packet_t;

union Packet
{
	uint32_t packetValue;
	struct
	{
		uint32_t crc:2;
		uint32_t status:1;
		uint32_t payload:12;
		uint32_t bat:3;
		uint32_t sensor:3;
		uint32_t longAddr:8;
		uint32_t shortAddr:2;
		uint32_t addrMode:1;
	} packetFields;
};

void PrintPacketData(union Packet *pData);
void wait_for_user_input();

int main(void)
{
	union Packet packet;
	union Packet *pPacket = &packet;

	printf("Enter the 32bit packet:\n");

	if(scanf("%X", &packet.packetValue) == 0)
	{
		printf("Failed!\n Incorrect input\n");
		wait_for_user_input();
		return 0;
	}

	PrintPacketData(pPacket);

	wait_for_user_input();

	return 0;
}

void PrintPacketData(union Packet *pData)
{
	printf("crc: %#x\n", pData->packetFields.crc);
	printf("status: %#x\n", pData->packetFields.status);
	printf("payload: %#x\n", pData->packetFields.payload);
	printf("bat: %#x\n", pData->packetFields.bat);
	printf("sensor: %#x\n", pData->packetFields.sensor);
	printf("longAddr: %#x\n", pData->packetFields.longAddr);
	printf("shortAddr: %#x\n", pData->packetFields.shortAddr);
	printf("addrMode: %#x\n", pData->packetFields.addrMode);

	printf("Size of packet(structure) %I64u\n", sizeof(*pData));
}

void wait_for_user_input()
{
	printf("Press enter to exit app\n");
	while(getchar() != '\n')
	{

	}
	getchar();
}
