/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct
{
	uint8_t crc;
	uint8_t status;
	uint16_t payload;
	uint8_t bat;
	uint8_t sensor;
	uint8_t longAddr;
	uint8_t shortAddr;
	uint8_t addrMode;
} Packet_t;

void CollectPacketData(Packet_t *pData, uint32_t rawData);
void PrintPacketData(Packet_t *pData);
void wait_for_user_input();

int main(void)
{
	Packet_t packet;
	Packet_t *pPacket = &packet;
	uint32_t rawData;

	printf("Enter the 32bit packet:\n");

	if(scanf("%X", &rawData) == 0)
	{
		printf("Failed!\n Incorrect input\n");
		wait_for_user_input();
		return 0;
	}

	CollectPacketData(pPacket, rawData);
	PrintPacketData(pPacket);

	wait_for_user_input();

	return 0;
}

void CollectPacketData(Packet_t *pData, uint32_t rawData)
{
	pData->crc = (uint8_t)(rawData & 0x03);

	pData->status = (uint8_t)((rawData >> 2) & 0x01);

	pData->payload = (uint16_t)((rawData >> 3) & 0x0FFF);

	pData->bat = (uint8_t)((rawData >> 15) & 0x07);

	pData->sensor = (uint8_t)((rawData >> 18) & 0x07);

	pData->longAddr = (uint8_t)((rawData >> 21) & 0xFF);

	pData->shortAddr = (uint8_t)((rawData >> 29) & 0x03);

	pData->addrMode = (uint8_t)((rawData >> 31) & 0x01);
}

void PrintPacketData(Packet_t *pData)
{
	printf("crc: %#x\n", pData->crc);
	printf("status: %#x\n", pData->status);
	printf("payload: %#x\n", pData->payload);
	printf("bat: %#x\n", pData->bat);
	printf("sensor: %#x\n", pData->sensor);
	printf("longAddr: %#x\n", pData->longAddr);
	printf("shortAddr: %#x\n", pData->shortAddr);
	printf("addrMode: %#x\n", pData->addrMode);

	printf("Size of packet(structure) %I64u\n", sizeof(*pData));
}

void wait_for_user_input()
{
	printf("Press enter to exit app\n");
	while(getchar() != '\n')
	{

	}
	getchar();
}
